# Generated by Django 4.2.4 on 2024-12-13 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_objectlookup_object_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvasiveSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=300)),
                ('species_name', models.CharField(max_length=300)),
                ('species_image', models.ImageField(null=True, upload_to='')),
                ('image_attribution', models.TextField(null=True)),
                ('description', models.TextField()),
                ('size', models.TextField()),
                ('color', models.TextField()),
                ('shape', models.TextField()),
                ('habitat', models.TextField()),
                ('native_to', models.TextField()),
                ('sort_order', models.IntegerField(default=1)),
                ('invasive_type', models.ForeignKey(limit_choices_to={'object_type': 'Invasive'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_object_lookups', to='common.objectlookup')),
            ],
            options={
                'verbose_name': 'Invasive Species',
                'verbose_name_plural': 'Invasive Species',
            },
        ),
    ]
