# Generated by Django 4.2.4 on 2023-10-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subproject',
            options={},
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='slug',
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
