# Generated by Django 4.2.4 on 2024-06-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_subproject_options_remove_subproject_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
