# Generated by Django 4.2.4 on 2024-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_subproject_sort_order_task_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='TaskNamePlaceholder', max_length=300),
        ),
    ]
