# Generated by Django 4.2.4 on 2024-12-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_for',
            field=models.CharField(choices=[('header', 'Header'), ('detail', 'Detail'), ('activity', 'Activity')]),
        ),
    ]
