# Generated by Django 4.2.4 on 2024-12-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_field_field_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='valueGetter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
