# Generated by Django 4.2.4 on 2023-08-14 16:27
from django.conf import settings
from django.db import migrations
from ..initial_data import populate_groups


class Migration(migrations.Migration):

    dependencies = [
       migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(populate_groups)
    ]
