# Generated by Django 4.2.4 on 2023-08-14 20:58

from django.db import migrations
from .initial_data import populate_groups


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('guardian', '0002_generic_permissions_index'),
        ('sessions', '0001_initial'),
        #('common', '0001_initial'),
        #('administration', '0001_initial'),
        # ('files', '0001_initial'),
        # ('account', '0001_initial'),
        # ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_groups)
    ]