# Generated by Django 4.2.4 on 2023-08-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/banner_default.JPG', upload_to='images/uploaded/'),
        ),
    ]
