# Generated by Django 4.2.4 on 2023-08-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_image_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='date',
            new_name='photo_date',
        ),
    ]
