# Generated by Django 4.2.4 on 2023-08-04 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Department Name')),
                ('description', models.TextField(verbose_name='Department Desecription')),
                ('banner', models.ImageField(default='images/department/wallowalake.JPG', upload_to='images/department/', verbose_name='Department Banner')),
                ('administrative_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_assist', to=settings.AUTH_USER_MODEL, verbose_name='Administrative Assistant')),
                ('deputy_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dept_deputy', to=settings.AUTH_USER_MODEL, verbose_name='Deputy Manager')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_manager', to=settings.AUTH_USER_MODEL, verbose_name='Department Manager')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
