# Generated by Django 4.2.4 on 2023-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('Office', 'Office'), ('Hatchery', 'Hatchery'), ('Other', 'Other')], default='Office'),
        ),
    ]
