# Generated by Django 4.2.4 on 2023-08-04 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0002_department_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Division Name')),
                ('description', models.TextField(verbose_name='Division Desecription')),
                ('banner', models.ImageField(default='images/division/wallowalake.JPG', upload_to='images/division/', verbose_name='Division Banner')),
                ('administrative_assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div_assist', to=settings.AUTH_USER_MODEL, verbose_name='Administrative Assistant')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.department', verbose_name='Division Department')),
                ('deputy_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div_deputy', to=settings.AUTH_USER_MODEL, verbose_name='Deputy Division Director')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='div_director', to=settings.AUTH_USER_MODEL, verbose_name='Division Director')),
            ],
        ),
    ]
