# Generated by Django 4.2.4 on 2023-08-08 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0003_remove_department_staff_remove_division_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='img_banner',
        ),
        migrations.RemoveField(
            model_name='department',
            name='img_card',
        ),
        migrations.RemoveField(
            model_name='division',
            name='img_banner',
        ),
        migrations.RemoveField(
            model_name='division',
            name='img_card',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_banner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img_card',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='img_banner',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='img_card',
        ),
        migrations.RemoveField(
            model_name='task',
            name='img_banner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='img_card',
        ),
        migrations.AddField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='division',
            name='staff',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subproject',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_project', to='administration.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='subproject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_subprojects', to='administration.subproject'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_leader',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_projct_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_lead', to=settings.AUTH_USER_MODEL),
        ),
    ]
