# Generated by Django 4.2.4 on 2023-08-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_division_options_alter_department_banner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_image1',
            new_name='banner',
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Project Created'),
        ),
    ]
