# Generated by Django 4.2.4 on 2023-08-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_image_image'),
        ('administration', '0005_alter_department_name_alter_division_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='img_banner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_banner', to='files.image'),
        ),
        migrations.AddField(
            model_name='department',
            name='img_card',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_card', to='files.image'),
        ),
        migrations.AddField(
            model_name='division',
            name='img_banner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_banner', to='files.image'),
        ),
        migrations.AddField(
            model_name='division',
            name='img_card',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_card', to='files.image'),
        ),
        migrations.AddField(
            model_name='project',
            name='img_banner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_banner', to='files.image'),
        ),
        migrations.AddField(
            model_name='project',
            name='img_card',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_card', to='files.image'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='img_banner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_banner', to='files.image'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='img_card',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_card', to='files.image'),
        ),
        migrations.AddField(
            model_name='task',
            name='img_banner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_banner', to='files.image'),
        ),
        migrations.AddField(
            model_name='task',
            name='img_card',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_card', to='files.image'),
        ),
    ]
