# Generated by Django 4.2.4 on 2024-11-05 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('photographer', models.CharField(max_length=50)),
                ('photo_date', models.DateField()),
                ('source', models.CharField(max_length=100)),
                ('image', models.ImageField(default='images/default.JPG', upload_to='images/uploaded/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display', models.BooleanField(default=True)),
                ('document', models.FileField(blank=True, max_length=200, upload_to='documents/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('primary_author', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
                ('citation', models.TextField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(limit_choices_to={'object_type': 'Document'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_object_lookups', to='common.objectlookup')),
                ('employee_authors', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_employee_authors', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
