# Generated by Django 4.2.4 on 2024-06-28 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0004_document_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, max_length=200, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='employee_authors',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_employee_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
