# Generated by Django 4.2.4 on 2023-08-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='photo',
        ),
    ]
