# Generated by Django 4.2.4 on 2023-08-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/profile_default.JPG', upload_to='images/profile/', verbose_name='Profile Picture'),
        ),
    ]
